### ISSUE TITLE
Prep 2.5

### ISSUE THREAD

**Issue by adam-urbanczyk** [CadQuery/cadquery#1725]
- [x] Merge outstanding PRs (#1593, #1713)
- [x] Final pass on free funcs (#1731)
- [x] Add arbitrary vtkActor rendering capabilities (#1726)
- [x] Restructure docs (#1736)
- [x] #1713
- [x] #1732

**Comment by adam-urbanczyk** [comment]
@jmwright @lorenzncode is there anything you'd like to add to the list?

**Comment by huskier** [comment]
Prior to the release of V2.5.0, I recommend enhancing the show function in the vis.py file by adding a new parameter named "title", which defaults to "CQ viewer".

`win.SetWindowName("CQ viewer")
`

```
def show(
    *objs: Showable,
    scale: float = 0.2,
    alpha: float = 1,
    tolerance: float = 1e-3,
    edges: bool = False,
    **kwrags: Any,
):
    """
    Show CQ objects using VTK.
    """
    ......
    # create a VTK window
    win = _vtkRenderWindow(assy, tolerance=tolerance)

    win.SetWindowName("CQ viewer")
```

**Comment by lorenzncode** [comment]
I have only #1713. As part of that I need to check whether any changes are required for the sphinx multimethod customization with sphinx version bump (and perhaps consider trying the `sphinx-immaterial` theme for docs as mentioned in #1697?).
